### PR TITLE
Update netdrive_es.po

### PR DESCRIPTION
**Pull request by Pjmh81**
Done

### CODE REVIEW

**Comment by yeonsh** [comment]
@Pjmh81, Hi!

This pull request is sent to your own repository. It need to be sent to bdrive/netdrive3-i18n repository for it to be merged.

Would you create a new pull request to bdrive/netdrive3-i18n repository?

**Comment by yeonsh** [comment]
If you add me as a member of your forked repository I will handle the pull request. :)

Thanks for your time!

**Comment by Pjmh81** [comment]
Done, please let me know if everything is ok.

**Comment by yeonsh** [comment]
Your translations successfully merged. Thanks!

**Pull request closed without merging**
